### ISSUE TITLE
Dependencies with '+' in version number mishandled

### ISSUE THREAD

**Issue by dubiousdavid** [clojure-emacs/cider-nrepl#208] opened 2015-05-20 18:40 UTC
This issue originally came up when using [vim-fireplace](https://github.com/tpope/vim-fireplace/). After some digging with the author of that plugin it was discovered that the issue was actually with cider-nrepl, which that plugin attempts to use if present.

The easiest thing at this point for me is to just link to that issue. If you need any clarification please let me know.

https://github.com/tpope/vim-fireplace/issues/217

**Comment by expez** [comment] 2015-06-12 17:13
> The easiest thing at this point for me is to just link to that issue.

That might be the case, but could you explain it like I'm five anyway?

**Comment by bbatsov** [comment] 2015-07-09 20:10
Ping :-)

**Comment by dubiousdavid** [comment] 2015-07-09 20:57
Basically, if you have a '+' in your artifact id, it get's replaced with a blank space, and the file path to the jar is incorrect.

**Comment by bbatsov** [comment] 2015-07-09 21:12
Hmm, the related Clojure code is pretty simple:

```
(defn classpath []
  (map #(URLDecoder/decode (str %) "utf-8") (cp/classpath)))
```

Likely `decode` is messing things up.

**Comment by bbatsov** [comment] 2015-07-09 21:14
Yep, according to its documentation `decode` converts `+` to space. Not sure what we can do about this. Maybe it's just a bad idea to use `+` in artefact names.

**Comment by arrdem** [comment] 2015-07-09 21:37
So, here we use + as part of our version numbers to indicate that we are "ahead" of some previous version on a snapshot. While + may have URL semantics, it is pretty clearly an acceptable token in a Maven version string and I would say that allowing it to URL decode to something other than + is a bug rather than something we can just punt on.

It would seem to me that if we're expecting to map over Seq[URL], the above is correct and the issue isn't there, the issue is a type bug in cp/classpath in that it can return a Seq of strings which have not been correctly URL encoded as the URL encode of + is %2something.

**Comment by bbatsov** [comment] 2015-07-10 06:16
> So, here we use + as part of our version numbers to indicate that we are "ahead" of some previous version on a snapshot.

I see. I've have never seen this so far. 

> It would seem to me that if we're expecting to map over Seq[URL], the above is correct and the issue isn't there, the issue is a type bug in cp/classpath in that it can return a Seq of strings which have not been correctly URL encoded as the URL encode of + is %2something.

This has to be checked. To be honest I don't remember the details and I have to consult the code to recover them. But I guess everyone can do this as it doesn't require any specific cider/nrepl knowledge.

**Comment by Malabarba** [comment] 2016-05-05 22:43
Is this still an issue?

**Comment by SevereOverfl0w** [comment] 2017-07-08 08:39
I think this was fixed by https://github.com/clojure-emacs/cider-nrepl/commit/cf451db14abd7615597a51b2b53b4815d604c3e3

Running a test locally, this seems to be fixed. A library with `+` in the version is still `+` in the output from `{:op "classpath"}`.

**Comment by bbatsov** [comment] 2017-07-08 09:16
@SevereOverfl0w Thanks for looking into this! (and for your help with the open issues) Much appreciated! 👍

**Comment by arrdem** [comment] 2017-07-09 02:07
🤘

**Closed by arrdem** 2017-07-09 02:07 UTC
