### ISSUE TITLE
Side Effects in top level code => breaks use in compiled scenarios

### ISSUE THREAD

**Issue by jsa-aerial** [clojure-emacs/cider-nrepl#533] opened 2018-05-29 16:59 UTC
See how and when delayed-handlers is updated, and also that cider-nrepl-handler is built as a side-effecting top level form.  This is the cause of (for example) #447. The key thing to note in the hack to work around this as presented in that issue is that cider.nrepl _cannot_ be required at _compile_ time (as in a ns form). So, until this is fixed, that should be explicitly mentioned (in bold!) in the documented workaround.

## Expected behavior
Embedding an nREPL server in compiled situations (for example, uberjar application) by explicitly using / constructing middleware  using cider.nrepl/cider-nrepl-handle supports connections with no problem

## Actual behavior
Embedding an nREPL server in compiled situations (for example, uberjar application) by explicitly using / constructing middleware  using cider.nrepl/cider-nrepl-handler results in NPE on any connection

## Steps to reproduce the problem
1. Embed an nREPL server by requiring cider.nrepl in an ns form
2. Connect to the server using the Emacs CIDER client

### cider-nrepl version
Any version of cider.nrepl since Sep 2017. The one I used was 0.17.0  The problem is how the deferred middleware was implemened

### Java version

1.8

### Operating system

Linux

**Comment by bbatsov** [comment] 2018-06-16 07:30
Yeah, I guess we overlooked this initially. Hopefully @vspinu can take a look at this once he's done with the connection rework.

**Comment by vspinu** [comment] 2018-06-16 17:05
Unless I miss something this is an exact duplicate of #447 and #464.

**Comment by jsa-aerial** [comment] 2018-06-17 18:21
Sort of - Bozhidar explicitly asked me to make this issue (on Slack) as it explicitly notes that the problem is due to side effecting top level forms and where and how those effects are happening. Neither of the other two (I actually reference #447 in the description...) note the base problem or where it occurs.

If you want to get rid of this issue - go for it. Doesn't matter to me as long as it gets corrected

**Comment by vspinu** [comment] 2018-06-17 20:10
>  explicitly notes that the problem is due to side effecting top level forms and where and how those effects are happening.

I am afraid this is not that helpful (to me at least). By "side-effecting" you presumably mean updating the delays atom. Ok, and? What problems does that cause and through which mechanism more concretely? Do you have a proposal for an alternative implementation?

I will have a close look. It bit enough people that an intervention or an alternative middleware loader seems necessary.

**Comment by jsa-aerial** [comment] 2018-06-17 21:56
Absolutely - updating the delayed-handlers at compile time and running the code for cider-nrepl-handler at top level is guaranteed to not work in any AOT (uberjar with main for example) situation. That's due to the fact the namespace must be loaded in order to compile the one requiring it. That will always invoke all top level side effects.  So, you have to change all of that so that nothing happens until runtime. Best way is to remove the updates from the macro(s) and have an initialization _function_ which is used at startup to initialize things.

Have a look at the answer to this as it might help you:

https://stackoverflow.com/questions/32288195/why-lein-uberjar-evaluates-variables-defined-with-def

If none of this helps, I really don't know what else to say...

**Comment by arohner** [comment] 2019-08-22 15:36
I just encountered this as well

**Comment by bbatsov** [comment] 2020-11-24 18:51
This should be fixed now - see #684.

**Closed by bbatsov** 2020-11-24 18:51 UTC
Labels: bug
