### ISSUE TITLE
The debugger isn't contextually in the right ns during evaluation

### ISSUE THREAD

**Issue by expez** [clojure-emacs/cider-nrepl#420] opened 2017-06-30 15:08 UTC
When I hit <kbd>e</kbd> to evaluate some code, while stepping through code in `my.namespace`, i expect to be able to use `::k` to look up the key `my.namespace/k` in maps.  Instead `::k` resolves to `:user/k` and the map lookup returns `nil`.

**Comment by vspinu** [comment] 2017-07-14 17:40
I think this is a duplicate of clojure-emacs/cider#2004

**Comment by vspinu** [comment] 2017-08-08 00:57
It's actually not a duplicate. It turned out that this issue is with the reading forms in wrong namespace, the clojure-emacs/cider#2004 is about evaluating forms in wrong ns and clojure-emacs/#2039 is about instrumenting in wrong ns. Funny that all these were reported more or less simultaneously only now.

**Closed** 2017-08-10 05:49 UTC
Labels: bug
