### ISSUE TITLE
New cider-nrepl cannot find see-also.edn

### ISSUE THREAD

**Issue by achesnais** [clojure-emacs/cider-nrepl#355] opened 2016-05-11 07:00 UTC
I launched my repl as I usually do this morning, and lein automatically downloaded the new cider-nrepl-0.13.0-SNAPSHOT.

## Expected behavior
I expect my repl to launch normally :)

## Actual behavior
I get this error (top of my stacktrace):

`clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: resources/see-also.edn (No such file or directory), compiling:(info.clj:143:38)`

## Steps to reproduce the problem
Not sure. I tried launching other projects but got the same same issue.

### cider-nrepl version

0.13.0-SNAPSHOT

### Java version

1.8

### Operating system

MacOSX El Capitan

**Comment by arrdem** [comment] 2016-05-11 07:01
Duplicate of #354

**Closed** 2016-05-11 13:44 UTC
