### ISSUE TITLE
Autocompletion working inconstantly on shadow cljs project. 

### ISSUE THREAD

**Issue by drewverlee** [clojure-emacs/cider-nrepl#732] opened 2021-12-02 03:07 UTC
## Expected behavior

Given a connected nrepl, started by shadow-cljs, if i require a namespace such as re-frame, i expect to get autocompletion consistently when my cursor is at the end of the var after a forward slash e.g re-frame/* should show results for existing vars in that ns e.g ->interceptor. 

It's worth noting, that this works sporadically in the project, in different namespaces. There are no noticeable differences in the namespaces. They are on the same deps path. Generally i have found that when it doesn't autocomplete it never does, when it does, it works 4/5 times, so it seems like there is some core difference that i can't detect. 

I tested it in both spacemacs and doom, far far more in the former. 

## Actual behavior

Quite often I'll get [no matches]. 

## Steps to reproduce the problem

I have created a toy example that demonstrates an issue (if not the full set) of problems with autocompletion. 

see https://github.com/drewverlee/toy/blob/d034e936b8cec2aa5bf07d0e400a3cb7a768badf/src/main/toy/m2.cljs#L5

1. in project run `cider-jack-in-cljs` then shadow -> browser build 
2. eval `(ns toy.m2 (:require [toy.m1 :as m1]))` 
3. type `m1/` then hit tab
4. expect to see m1/blah bu instead see nothing
5. eval m1/blah correctly returns "blah"
6. type m1/ then hit tab it correctly returns m1/blah

at a high level the issue looks like:

1. follow a quick start shadow guide for shadow cljs
2. grow the project to a large enough size
3. require a namespace, try auto-completion described in "expected behavior".

I know this isn't a reliable way to reproduce the behavior, that's likely why this issue hasn't been addressed. I would love some ideas on how to be more specific though. I can't provide the code for the specific project i'm working on, but i could provide diagnostic information if i knew how to get it and what would be useful. 

### cider-nrepl version

Cider 1.2.0snapeshot

CLJS clients@localhost:38897 (Java 11.0.11, Clojure 1.10.3, nREPL 0.9.0-beta5)
progn: Beginning of buffer [17 times]
CIDER 1.2.0snapshot (package: 20211126.1158)

### Java version

 11.0.11,

### Operating system

➜  ~  lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

#### extra

I asked user @vemv about how to start diagnosing this issue and he provided some feedback that I think is relevant at least for my own bookkeeping:

> cider-nrepl provides completions. It does so by invoking Compliment which is a clj library. Compliment is based on "sources" i.e. a completion provider. There's a source specifically for cljs completions, provided by a library called clj-suitable
cider-nrepl is a vanilla ns. so are Compliment and clj-suitable. However compliment and clj-suitable are prefixed with cider-nrepl-something-something (https://github.com/benedekfazekas/mranderson does that munging)
If you invoke (all-ns) you should find cider-nrepl, and the 'munged' versions of compliment and clj-suitable.
These are all JVM clojure libs. So jump-to-definition should work. You can take a look around their repos as well (edited) 
benedekfazekas/mranderson

**Comment by vemv** [comment] 2021-12-02 03:43
Probably a great way to iterate/debug would be to invoke approximately the following code in CIDER's JVM repl:

```clj
(cider.nrepl.middleware.complete/complete {:ns 'my.ns
                                           ;; grab all functions starting by c:
                                           :prefix "c"})
```

It works but that's for JVM completions. For cljs completions to be offered, the hashmap argument needs to have a "cljs env" as part of it. Not sure of how to do that programatically. Might be easy for @bbatsov?

---

A related point that might have actually have to do with the root problem, is that the mentioned cljs env has to be always up to date. I reckon that as one saves files, shadow-cljs updates the cljs env?

So said object should also be kept up-to-date in the nrepl messages we pass.

It's not an area I'm intimately familiar with.

**Comment by bbatsov** [comment] 2021-12-02 07:54
I guess at some point I should update https://docs.cider.mx/cider/1.1/cljs/overview.html#limitations :-) It has long been on my todo list to explain better why a lot of things don't in ClojureScript or work differently (although the explanation for everything is more or less the same). 

In the case of ClojureScript the completion candidates are pulled from the cljs env indeed. (see https://github.com/clojure-emacs/orchard/blob/master/src/orchard/cljs/analysis.cljc and https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/complete.clj#L49) My knowledge of ClojureScript is pretty basic and I never used it myself for anything, which is the primary reason the ClojureSupport in CIDER is so basic. 

> It works but that's for JVM completions. For cljs completions to be offered, the hashmap argument needs to have a "cljs env" as part of it. Not sure of how to do that programatically. Might be easy for @bbatsov?

The clj env call be pulled from Piggieback on the Clojure side (and shadow-cljs provides a Piggieback emulation to work with cider-nrepl/CIDER). If one just wants to see what's returned as completion candidates it's better the just invoke the Elisp functions in IELM. (e.g. `cider-sync-request:complete`) The results should also be visible in CIDER's nREPL log buffer.

**Comment by drewverlee** [comment] 2021-12-02 20:30
I'll update the ticket to reflect this but i am running clojure LSP as well `LSP :: lsp-mode 20211201.1200, Emacs 27.2, gnu/linux`

Though nothing in my spacemacs config specifically enables autocompletion 

Part of my confusion is how to tell what is providing the autocompletion in the first place. Here is a dump of my spacemacs config setup

```
(clojure :variables
              cider-repl-display-help-banner nil      ;; disable help banner
              cider-pprint-fn 'fipp                   ;; fast pretty printing
              ;; can't use because it auto indents other peoples code
              clojure-indent-style 'align-arguments
              clojure-align-forms-automatically t
	            cider-result-overlay-position 'at-eol
              cider-overlays-use-font-lock t
              clojure-enable-fancify-symbols t
              clojure-enable-clj-refactor t
              clojure-toplevel-inside-comment-form t
              cider-repl-buffer-size-limit 1000
              ;; Need very recent version of spacemacs to enable as a linter
              ;; otherwise see https://github.com/borkdude/clj-kondo/blob/master/doc/editor-integration.md#spacemacs

              ;; 
              ;; TODO requires installing clj Kondo

	      ;; This is now part of clojure-lsp
	      ;; https://practicalli.github.io/spacemacs/install-spacemacs/clojure-lsp/configure-lsp-and-cider.html
              ;; clojure-enable-linters 'clj-kondo
	      )
	      
	         ;; Language server protocol with minimal visual impact
     ;; https://practicalli.github.io/spacemacs/install-spacemacs/clojure-lsp/lsp-variables-reference.html
     (lsp :variables
          ;; Formatting and indentation - use Cider instead
          lsp-enable-on-type-formatting nil
          ;; Set to nil to use CIDER features instead of LSP UI
          lsp-enable-indentation nil
          lsp-enable-snippet t  ;; to test again

          ;; symbol highlighting - `lsp-toggle-symbol-highlight` toggles highlighting
          ;; subtle highlighting for doom-gruvbox-light theme defined in dotspacemacs/user-config
          lsp-enable-symbol-highlighting t

          ;; Show lint error indicator in the mode line
          lsp-modeline-diagnostics-enable t
          ;; lsp-modeline-diagnostics-scope :workspace

          ;; popup documentation boxes
         lsp-ui-doc-enable nil          ;; disable all doc popups
          lsp-ui-doc-show-with-cursor nil   ;; doc popup for cursor
          ;; lsp-ui-doc-show-with-mouse t   ;; doc popup for mouse
          ;; lsp-ui-doc-delay 2                ;; delay in seconds for popup to display
          lsp-ui-doc-include-signature t    ;; include function signature
          ;; lsp-ui-doc-position 'at-point  ;; top bottom at-point
          lsp-ui-doc-alignment 'window      ;; frame window

          ;; code actions and diagnostics text as right-hand side of buffer
          lsp-ui-sideline-enable nil
          lsp-ui-sideline-show-code-actions nil
          ;; lsp-ui-sideline-delay 500

          ;; lsp-ui-sideline-show-diagnostics nil

          ;; reference count for functions (assume their maybe other lenses in future)
          lsp-lens-enable t

          ;; Efficient use of space in treemacs-lsp display
          treemacs-space-between-root-nodes nil

          ;; Optimization for large files
          lsp-file-watch-threshold 1000000
          lsp-log-io nil)


	      
	      
	      
	      
	      ```

**Comment by vemv** [comment] 2021-12-03 06:18
Yeah we didn't know you used LSP until now, which makes the issue a little bit denser.

Can you try as @bbatsov suggests? Namely:

> it's better the just invoke the Elisp functions in IELM. (e.g. cider-sync-request:complete) The results should also be visible in CIDER's nREPL log buffer.

https://github.com/clojure-emacs/cider/blob/9d4c46f9cc9c49ffa75ce687db27a775bb9b2d9f/cider-client.el#L617-L627

You can get a context via `(cider-completion-get-context)`.

See more here: https://github.com/clojure-emacs/cider/blob/9d4c46f9cc9c49ffa75ce687db27a775bb9b2d9f/cider-completion.el#L178-L195

**Comment by drewverlee** [comment] 2021-12-04 15:17
@vemv i tried. with a running shadow project in another buffer:

```
ELISP> (cider-sync-request:complete "re-frame" (cider-completion-get-context) )
*** Eval error ***  No linked CIDER sessions
```

1. I assume the first arg "re-frame" needs to be something else.
2. How do I resolve that error? I googled around and found nothing.

**Comment by vemv** [comment] 2021-12-04 15:43
Try it in the same buffer? Via M-: https://www.gnu.org/software/emacs/manual/html_node/emacs/Lisp-Eval.html

**Comment by drewverlee** [comment] 2021-12-04 20:18
> The results should also be visible in CIDER's nREPL log buffer. @bbatsov 

Here is an example nrepl log buffer message that occurred when it failed to autocomplete:

```
(-->
  id         "116"
  op         "eldoc"
  session    "9b2fd9c1-692d-418f-8438-844588355dca"
  time-stamp "2021-12-04 14:15:43.363100585"
  ns         #("admin.events.containers.activity-resources" 0 42 (fontified t help-echo cider--help-echo cider-locals nil cider-block-dynamic-font-lock t face font-lock-type-face))
  sym        "kyber-db/"
)
(<--
  id         "116"
  session    "9b2fd9c1-692d-418f-8438-844588355dca"
  time-stamp "2021-12-04 14:15:43.391744387"
  status     ("done" "no-eldoc")
)
```

code it refers to minimally...
```
(ns admin.events.containers.activity-resources
  (:require 
            [kyber.lib.kyber-db :as kyber-db]))


;;doestn work autocomplete if cursor at kyber-db/* and i hit tab. 
kyber-db/
```

**Comment by vemv** [comment] 2021-12-04 22:44
The `op` is different. In the 'failing' case it's `eldoc`. That's not what you're looking after - it's `complete` always.

Maybe it's logged right below/above that one?

**Comment by drewverlee** [comment] 2021-12-05 01:19
I'll paste everything next time, but the log segment i posted is what's outputed when you run the command. It was even a different color.

**Comment by drewverlee** [comment] 2021-12-05 04:33
when i hit tab and autocomplete works i get the following in my Nrepl log:
```


(<--
  id          "235"
  session     "9b2fd9c1-692d-418f-8438-844588355dca"
  time-stamp  "2021-12-04 22:31:08.429603084"
  completions ((dict "candidate" "re-frame/path" "ns" "re-frame.core" "type" "var") ...)
  status      ("done")
)
```
Nothing comes back in the logs.

**Comment by drewverlee** [comment] 2021-12-05 04:58
I toggled cider mode on the file with no autocomplete and it then completed as hoped. Maybe that helps? Cider mode was on when it was failing.

**Comment by vemv** [comment] 2021-12-05 12:28
There is still missing a `complete` request that fails or returns an empty result. It should be triggered either by natural usage, or intentionally via `M-:` as suggested in prior posts.

(The former would be prefered)

Without that info we cannot discard hypotheses.

**Comment by vemv** [comment] 2021-12-11 07:13
@drewverlee : did you have luck observing in the logs a failed `complete` request?

If you cannot find one at all - most likely that indicates the problem itself, i.e. something else such as clojure-lsp is performing the completion, instead of CIDER.

If indeed no `complete` request is sent probably I'd recommend tracing what your emacs is doing, step by step. There can be quite a few moving parts (which vary themselves depending on your distro of choice, local tweaks etc) so probably this is not something we could debug for end users.

**Comment by drewverlee** [comment] 2021-12-11 20:28
the nrepl log doesn't register a "complete" request when i tab-complete. 
 
 Currently, tab completion works even if i'm not jacked in, so i assume it is LSP that's currently doing it. This improved situation might come from aving LSP watch a smaller set of tiles. 
 
 if i press `M-:` or as i understand it Ctrl + shift + ;  i just get a : character. what command is associated with that shortcut?

**Comment by vemv** [comment] 2021-12-19 19:29
Sorry forgot to reply, it's easily findable anyway https://www.gnu.org/software/emacs/manual/html_node/emacs/Lisp-Eval.html

> Currently, tab completion works even if i'm not jacked in, so i assume it is LSP that's currently doing it. 

I think the nature of the issue is pretty clear by now. Anyway it has been good to summarize how to debug these.

Closing, please feel free to reopen if you think there's something to be done cider-side (with the caveats mentioned above i.e. `probably this is not something we could debug for end users`).

Cheers - V

**Closed by vemv** 2021-12-19 19:29 UTC
