### ISSUE TITLE
Middleware fail starting nREPL in VSCode

### ISSUE THREAD

**Issue by bhlieberman** [clojure-emacs/cider-nrepl#757] opened 2022-09-14 03:22 UTC
## Expected behavior

Cider nREPL starts in VSCode for CLJS project without any exceptions being thrown.

## Actual behavior

The REPL still starts and my CLJS project builds but I get this stack trace: 
```
[2022-09-13 21:09:22.474 - WARNING] :shadow.cljs.devtools.server.nrepl/middleware-fail - {:sym cider.nrepl/cider-middleware}
Note: The following stack trace applies to the reader or compiler, your code was not executed.
CompilerException Syntax error compiling at (cider/nrepl.clj:1:1). #:clojure.error{:phase :compile-syntax-check, :line 1, :column 1, :source "cider/nrepl.clj"}
        clojure.lang.Compiler.load (Compiler.java:7648)
        clojure.lang.RT.loadResourceScript (RT.java:381)
        clojure.lang.RT.loadResourceScript (RT.java:372)
        clojure.lang.RT.load (RT.java:459)
        clojure.lang.RT.load (RT.java:424)
        clojure.core/load/fn--6839 (core.clj:6126)
        clojure.core/load (core.clj:6125)
        clojure.core/load (core.clj:6109)
        clojure.core/load-one (core.clj:5908)
        clojure.core/load-one (core.clj:5903)
        clojure.core/load-lib/fn--6780 (core.clj:5948)
        clojure.core/load-lib (core.clj:5947)
Caused by:
IllegalAccessError with-session-classloader does not exist
        clojure.core/refer (core.clj:4249)
        clojure.core/refer (core.clj:4217)
        clojure.core/apply (core.clj:667)
        clojure.core/load-lib (core.clj:5966)
        clojure.core/load-lib (core.clj:5928)
        clojure.core/apply (core.clj:667)
        clojure.core/load-libs (core.clj:5985)
        clojure.core/load-libs (core.clj:5969)
        clojure.core/apply (core.clj:667)
        clojure.core/require (core.clj:6007)
        clojure.core/require (core.clj:6007)
        cider.nrepl/eval7083/loading--6721--auto----7084 (nrepl.clj:1)
```

## Steps to reproduce the problem

1. Start a basic CLJS project with `npx create-cljs-app`.
2.  Open it in VSCode.
3.  Connect to the REPL using the status bar on the bottom. Select `shadow-cljs` as project type and `:app` as build to watch.
4.  Some normal output `npx shadow-cljs -d cider/cider-nrepl:0.28.5 watch :app` should appear followed by above stacktrace.
5. Then the project keeps building.

### cider-nrepl version

0.28.5

### Java version

`java --version`: `openjdk 17.0.4 2022-07-19`

### Operating system

Windows 11/WSL Ubuntu 20.04

**Comment by bbatsov** [comment] 2022-09-19 15:40
I can't reproduce this, but I've also seen occasionally weird random errors about compilation warnings. No idea what causes them, though.

**Comment by bhlieberman** [comment] 2022-09-19 18:34
I'm pretty new to CLJS but this is definitely the first time I've seen it. I was having some issues with hot reloading in Shadow CLJS so I was doing frequent REPL restarts. I think that's when I first saw the error. It looks like the `:jvm-opts ["--illegal-access" "deny"]` workaround from Clojure is not an option, even if it were able to fix this. Not sure.

**Comment by vemv** [comment] 2023-09-20 13:34
I'll close this one as it's been a while - if it still was a problem we would have known.

Do feel free to continue the conversation!

**Closed** 2023-09-20 13:34 UTC
Labels: bug
