### ISSUE TITLE
Deploy SNAPSHOT builds after successful Travis builds of `master`

### ISSUE THREAD

**Issue by cichli** [clojure-emacs/cider-nrepl#194] opened 2015-04-23 11:52 UTC
Should be a matter of running `lein deploy clojars` in [`after_success`](http://docs.travis-ci.com/user/build-configuration/#build-lifecycle) (for `master` only) and ensuring the correct environment variables for the credentials are in place [here](https://travis-ci.org/clojure-emacs/cider-nrepl/settings/env_vars).

**Comment by bbatsov** [comment] 2015-04-23 11:56
Yeah, this has been in my todo since forever. Actually now it's a matter of running `./build.sh deploy clojars`, but the core idea is the same.

**Comment by cichli** [comment] 2015-04-26 08:31
See travis-ci/travis-ci#929

**Comment by gonewest818** [comment] 2018-02-14 16:23
This is a duplicate of #497, which is done.

**Closed** 2018-02-14 17:31 UTC
Labels: enhancement
