### ISSUE TITLE
Santax error starting `lein repl` with OpenJDK 11, 12, 14, 16 with :plugin cider-nrepl

### ISSUE THREAD

**Issue by Rovanion** [clojure-emacs/cider-nrepl#724] opened 2021-10-31 11:48 UTC
## Expected behavior
With a `project.clj` like

```
(defproject cider-nrepl-syntax-error "0.1.0"
  :description  "A bug demonstration"
  :url          "http://example.com"
  :dependencies [[org.clojure/clojure "1.10.3"]]  ; The language itself.                                               
  :plugins [[cider/cider-nrepl "0.26.0"]])
```

on a Guix System with Leiningen 2.9.7 on Java 14 OpenJDK 64-Bit Server VM, when running `lein repl` I expect to get a normal readline Clojure REPL.

## Actual behavior
Instead the following error is thrown:

```
ERROR: Unhandled REPL handler exception processing message {:code (clojure.core/binding [clojure.core/*ns* (clojure.core/or (clojure.core/find-ns (clojure.core/symbol "reply.eval-modes.nrepl")) clojure.core/*ns*)] (set! *print-length* nil)), :id f2cf2945-b29b-4314-b685-2ab703bb08c9, :op eval, :session d4f9b77c-8e83-4e1d-91ae-f6dc0d06e6bd}
Syntax error compiling at (cider/nrepl/inlined_deps/orchard/v0v7v1/orchard/java/parser.clj:1:1).
```

along with the following amazingly long stacktrace

```
	at clojure.lang.Compiler.load(Compiler.java:7652)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3706)
	at clojure.lang.Compiler$BodyExpr.eval(Compiler.java:6138)
	at clojure.lang.Compiler$IfExpr.eval(Compiler.java:2733)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7186)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:619)
	at cider.nrepl.inlined_deps.orchard.v0v7v1.orchard.info$eval3993$loading__6737__auto____3994.invoke(info.clj:1)
	at cider.nrepl.inlined_deps.orchard.v0v7v1.orchard.info$eval3993.invokeStatic(info.clj:1)
	at cider.nrepl.inlined_deps.orchard.v0v7v1.orchard.info$eval3993.invoke(info.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7170)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:930)
	at cider.nrepl.middleware.stacktrace$eval3985$loading__6737__auto____3986.invoke(stacktrace.clj:1)
	at cider.nrepl.middleware.stacktrace$eval3985.invokeStatic(stacktrace.clj:1)
	at cider.nrepl.middleware.stacktrace$eval3985.invoke(stacktrace.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7170)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:1289)
	at cider.nrepl.middleware.debug$eval3568$loading__6737__auto____3569.invoke(debug.clj:1)
	at cider.nrepl.middleware.debug$eval3568.invokeStatic(debug.clj:1)
	at cider.nrepl.middleware.debug$eval3568.invoke(debug.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7170)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cider.nrepl$handler_future$fn__2064.invoke(nrepl.clj:51)
	at clojure.lang.Delay.deref(Delay.java:42)
	at clojure.core$deref.invokeStatic(core.clj:2324)
	at clojure.core$deref.invoke(core.clj:2310)
	at cider.nrepl$wrap_debug$fn__2135.invoke(nrepl.clj:159)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_enlighten$fn__2143.invoke(nrepl.clj:186)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_clojuredocs$fn__2291.invoke(nrepl.clj:522)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_macroexpand$fn__2177.invoke(nrepl.clj:283)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_xref$fn__2283.invoke(nrepl.clj:507)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at nrepl.middleware.caught$wrap_caught$fn__915.invoke(caught.clj:97)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_spec$fn__2225.invoke(nrepl.clj:412)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_trace$fn__2249.invoke(nrepl.clj:460)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_refresh$fn__2209.invoke(nrepl.clj:376)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl.middleware.track_state$handle_tracker.invokeStatic(track_state.clj:240)
	at cider.nrepl.middleware.track_state$handle_tracker.invoke(track_state.clj:238)
	at clojure.lang.Var.invoke(Var.java:388)
	at cider.nrepl$wrap_tracker$fn__2257.invoke(nrepl.clj:478)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_profile$fn__2201.invoke(nrepl.clj:339)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at nrepl.middleware.completion$wrap_completion$fn__1414.invoke(completion.clj:50)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_version$fn__2275.invoke(nrepl.clj:497)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_resource$fn__2217.invoke(nrepl.clj:402)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at nrepl.middleware.sideloader$wrap_sideloader$fn__1533.invoke(sideloader.clj:104)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at nrepl.middleware.dynamic_loader$wrap_dynamic_loader$fn__1150.invoke(dynamic_loader.clj:97)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_format$fn__2151.invoke(nrepl.clj:190)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at nrepl.middleware.print$wrap_print$fn__882.invoke(print.clj:234)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at cider.nrepl$wrap_out$fn__2193.invoke(nrepl.clj:330)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at nrepl.middleware.session$session$fn__1081.invoke(session.clj:309)
	at nrepl.middleware$wrap_conj_descriptor$fn__646.invoke(middleware.clj:16)
	at nrepl.server$default_handler$fn__1577.invoke(server.clj:130)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:22)
	at nrepl.server$handle_STAR_.invoke(server.clj:19)
	at nrepl.server$handle$fn__1548.invoke(server.clj:39)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: jdk.javadoc.doclet.Doclet
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2225)
	at cider.nrepl.inlined_deps.orchard.v0v7v1.orchard.java.parser$eval4218$loading__6737__auto____4219.invoke(parser.clj:1)
	at cider.nrepl.inlined_deps.orchard.v0v7v1.orchard.java.parser$eval4218.invokeStatic(parser.clj:1)
	at cider.nrepl.inlined_deps.orchard.v0v7v1.orchard.java.parser$eval4218.invoke(parser.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7170)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	... 191 more
```

If `[cider/cider-nrepl "0.26.0"]` is removed from the plugins vector the REPL starts as expected.

## Steps to reproduce the problem
This problem does not occur on my Ubuntu 20.04 machine (which I unfortunately don't have at hand at the moment).  I hope it will be possible to reproduce the issue by installing [Guix the package manager](https://guix.gnu.org/manual/en/html_node/Binary-Installation.html) on any Linux system and running

```
guix environment --ad-hoc leiningen
lein repl
```

while standing in a folder with the above `project.clj`. I have tried running with a "normally" installed Leiningen installed from the [shell script](https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein) with the same results.

Switching out the the JDK to IcedTea/OpenJDK 8 makes the problem disappear. You can do this by running

```
guix environment --ad-hoc icedtea bash which coreutils --pure
~/.local/bin/lein repl
```

The --pure flag will make sure that your shell is not polluted by anything but the packages Guix provides. Replace `~/.local/bin` with your systems specific path to Leiningen.

## Environment & Version information
Guix System 1.3 with Leiningen 2.9.7 on Java 14 OpenJDK 64-Bit Server VM.

### cider-nrepl version

0.26.0

### Java version
Nonworking:
OpenJDK 11.28
OpenJDK 12.33
OpenJDK 14.0.2
OpenJDK 16.0.1

Working:
OpenJDK/IcedTea 1.8.0_161-b12

### Operating system
Guix System 1.3.

**Comment by vemv** [comment] 2021-10-31 13:30
👋!

to begin with, Clojure itself and cider-nrepl don't particularly support non-LTS JDKs. So I'd recommend using 8, 11 or 17 instead. Likewise cider-nrepl latest is 0.27.2, please be wary of creating issue for older versions.

Anyway the problem is that for whatever reason `jdk.javadoc.doclet.Doclet` can't be imported. That's not much to be expected since it's part of the JDK.

It sounds like you're having an issue with the module system? See e.g. https://stackoverflow.com/a/65695874 . Perhaps the JDK that you're using was built in such a way that that module isn't available by default.

(Hint for quick iteration: a bare `lein repl` and then `(import 'jdk.javadoc.doclet.Doclet)` should succeed)

Personally I've never encounted the class not being available OOTB, neither on macOS or Linux (via CircleCI).

I'll close this issue as it's completely out of control for cider-nrepl, however a report back will be much appreciated.

**Closed by vemv** 2021-10-31 13:30 UTC

**Comment by vemv** [comment] 2022-02-15 22:37
A concrete fix is reflected in https://github.com/clojure-emacs/orchard/issues/152#issuecomment-1040864809

**Comment by Rovanion** [comment] 2022-02-16 09:17
Thanks!
