### ISSUE TITLE
cider eldoc-error when trying to show eldoc for a java call

### ISSUE THREAD

**Issue by xificurC** [clojure-emacs/cider-nrepl#621] opened 2019-06-26 09:06 UTC
## Expected behavior
cider works without throwing eldoc-errors in my face :)

## Actual behavior
cider throwing eldoc-errors in my face :)

## Steps to reproduce the problem
start cider nrepl, write (System/getenv ) and wait for eldoc. This only happens for java calls, e.g. (get ) won't break.

### cider-nrepl version

cider.nrepl.version/version
```clojure
 {:major 0,
 :minor 22,
 :incremental 0,
 :qualifier nil,
 :version-string "0.22.0-beta6"}
```
### Java version
```
;; CIDER 0.22.0snapshot (package: 20190625.1651), nREPL 0.6.0
;; Clojure 1.10.0, Java 1.8.0_191
```
### Operating system

ubuntu bionic

### complete error buffer

  Show: Project-Only All 
  Hide: Clojure Java REPL Tooling Duplicates  (31 frames hidden)

  This is an unexpected CIDER middleware error.
  Please submit a bug report via `M-x cider-report-bug`.

  If these stacktraces are occurring frequently, consider using the
  button(s) below to suppress these types of errors for the duration of
  your current CIDER session. The stacktrace buffer will still be
  generated, but it will "pop under" your current buffer instead of
  "popping over". The button toggles this behavior.

 Suppress eldoc-error 
```
1. Unhandled java.lang.NullPointerException
   (No message)

             UnixPath.java:   77  sun.nio.fs.UnixPath/normalizeAndCheck
             UnixPath.java:   71  sun.nio.fs.UnixPath/<init>
       UnixFileSystem.java:  281  sun.nio.fs.UnixFileSystem/getPath
                Paths.java:   84  java.nio.file.Paths/get
             classpath.clj:  122  cider.nrepl.inlined-deps.orchard.v0v5v0-beta8.orchard.classpath/classpath-file-relative-path
             classpath.clj:  114  cider.nrepl.inlined-deps.orchard.v0v5v0-beta8.orchard.classpath/classpath-file-relative-path
                  info.clj:  184  cider.nrepl.inlined-deps.orchard.v0v5v0-beta8.orchard.info/info*/fn
                  core.clj: 6196  clojure.core/update
                  core.clj: 6188  clojure.core/update
                  info.clj:  182  cider.nrepl.inlined-deps.orchard.v0v5v0-beta8.orchard.info/info*
                  info.clj:  161  cider.nrepl.inlined-deps.orchard.v0v5v0-beta8.orchard.info/info*
                  info.clj:   60  cider.nrepl.middleware.info/info
                  info.clj:   49  cider.nrepl.middleware.info/info
                  info.clj:   73  cider.nrepl.middleware.info/eldoc-reply
                  info.clj:   71  cider.nrepl.middleware.info/eldoc-reply
        error_handling.clj:  160  cider.nrepl.middleware.util.error-handling/eval27663/fn
              MultiFn.java:  234  clojure.lang.MultiFn/invoke
                  info.clj:   84  cider.nrepl.middleware.info/handle-info
                  info.clj:   83  cider.nrepl.middleware.info/handle-info
                  Var.java:  388  clojure.lang.Var/invoke
                 nrepl.clj:  180  cider.nrepl/wrap-info/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  336  cider.nrepl/wrap-refresh/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 print.clj:  234  nrepl.middleware.print/wrap-print/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  362  cider.nrepl/wrap-resource/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  419  cider.nrepl/wrap-trace/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  437  cider.nrepl/wrap-tracker/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                 nrepl.clj:  290  cider.nrepl/wrap-out/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
               session.clj:  272  nrepl.middleware.session/session/fn
            middleware.clj:   16  nrepl.middleware/wrap-conj-descriptor/fn
                server.clj:   18  nrepl.server/handle*
                server.clj:   15  nrepl.server/handle*
                server.clj:   27  nrepl.server/handle/fn
                  core.clj: 2030  clojure.core/binding-conveyor-fn/fn
                  AFn.java:   18  clojure.lang.AFn/call
           FutureTask.java:  266  java.util.concurrent.FutureTask/run
   ThreadPoolExecutor.java: 1149  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  624  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  748  java.lang.Thread/run

```

**Comment by bbatsov** [comment] 2019-06-26 09:21
Looks like a regression in Orchard - @jeffvalk can you take a look?

**Comment by jeffvalk** [comment] 2019-06-26 22:36
@bbatsov The function that throws that exception (`classpath-file-relative-path`) looks like it came from [re-enabling][1] the boot hacks. You know my thoughts on that. :-)

@arichiardi Is there a test case that needs to be added to prevent this?

[1]: https://github.com/clojure-emacs/orchard/commit/fa782a156bafdb92ef8147702b5baa7d0058a551

**Comment by arichiardi** [comment] 2019-06-26 22:42
Thanks for reporting, I can debug that, don't know about test case yet because I don't know the problem yet 😃

Will check, sorry, these things shouldn't happen but they happen 👍

**Comment by arichiardi** [comment] 2019-06-26 22:43
@xificurC I assume you are in a boot project, please let me know if you actually are not, it can help with the debugging.

**Comment by arichiardi** [comment] 2019-06-27 02:38
Tried in a `boot` project with

```
boot -i "(require 'cider.tasks)" -d nrepl\:0.6.0 -d cider/cider-nrepl\:0.22.0-beta6 ...
```

and can't reproduce, does this happen in `lein` projects (will check as well) ?

**Comment by xificurC** [comment] 2019-06-27 05:47
Hi @arichiardi , it was in a boot project. Did you copy that boot command from emacs? It was eldoc that triggered this bug, just want to make sure you tried the same use case.

**Comment by arichiardi** [comment] 2019-06-27 17:19
@xificurC I don't really see...it seems that here after the completions kick in and complete `System/getenv` make the space and wait, nothing really happens.

**Comment by arichiardi** [comment] 2019-06-27 17:22
I am on `cider` commit 82acdf7a

**Comment by arichiardi** [comment] 2019-06-27 18:29
Nope cannot repro, I have tried two different boot projects here (one clj and one cljs) but nothing is triggering the error and I see `eldoc` with `(get )`.

My next question would be if you have a project to share that I can debug on.

**Comment by xificurC** [comment] 2019-06-28 14:01
Sorry I'm really busy at work right now. I managed to take a quick look now as eldoc is just blowing up all the time. I tried to look into some of the function calls. The deepest I got is

```
(ns ^{:mranderson/inlined true} cider.nrepl.inlined-deps.orchard.v0v5v0-beta8.orchard.info
```

where `info*` goes into the `update` call and `file-path` is sometimes nil. This blows up the whole thing. I'll try to debug some more to see how deep this particular rabbit hole is.

Don't have a config to share right now, sorry, I'll see if I can whip up something.

**Comment by arichiardi** [comment] 2019-06-28 14:46
Ok thank you that might be enough will take a look at that as well.

**Comment by xificurC** [comment] 2019-07-01 10:01
Debugging this some more I came to the following conclusion:

- `eldoc-reply` calls `(info msg)`
- `info` calls `info/info*` for the clojure case
- `info*` calls the boot hack with the `:file` key of the given map. The supplied map built by `info` **never** has a `:file` key. This results in calling the boot hack with `nil`, which blows up somewhere deep.

My quick solution is to change `info*` in `(ns ^{:mranderson/inlined true} cider.nrepl.inlined-deps.orchard.v0v5v0-beta8.orchard.info`, specifically the call

```clojure
(update :file (fn [file-path]
                     (if (u/boot-project?)
                       (cp/classpath-file-relative-path file-path)
                       file-path)))
```

to

```clojure
(update :file (fn [file-path]
                     (if (u/boot-project?)
                       (and file-path (cp/classpath-file-relative-path file-path))
                       file-path)))
```

This solves the NPE. Another option would be to push the `nil` check into `classpath-file-relative-path`. I'm not very keen on further contemplating whose responsibility this is or why the first error was on a java call and now it's on clojure calls, I'm just happy this solves my issue and makes emacs/cider usable again. I'll leave the choice of how to fix this up to you guys :) Thank you for your help

**Comment by arichiardi** [comment] 2019-07-01 23:05
Thank you very much for the debugging, it is weird though the the file path is nil there, I suspect something else is the cause.

Probably in this case we should filter our this call completely when there is no file path coming from info.

**Comment by xificurC** [comment] 2019-07-02 06:27
I see I forgot that `info*` calls `clj-meta` which calls into various `orchard.meta` functions depending on the supplied map. I recall I had crashes yesterday when my cursor was on `finally`:

```clojure
cider.nrepl.inlined-deps.orchard.v0v5v0-beta8.orchard.info> (clj-meta {:dialect :clj :ns 'clojure.core :sym 'finally})
{:forms [(try expr* catch-clause* finally-clause?)],
 :doc
 "catch-clause => (catch classname name expr*)\n  finally-clause => (finally expr*)\n\n  Catches and handles Java exceptions.",
 :name finally,
 :special-form true,
 :url "https://clojure.org/special_forms#finally"}
```

There's no `:file` there. Based on this observation I would say the `(update :file` code is incorrect and should be checked whether `:file` is actually not nil.

**Comment by bbatsov** [comment] 2020-02-07 08:00
I think that's fixed now.

**Closed by bbatsov** 2020-02-07 08:00 UTC
