### ISSUE TITLE
latest 0.18.0-SNAPSHOT broken:  No matching ctor found for class java.net.InetSocketAddress

### ISSUE THREAD

**Issue by hagmonk** [clojure-emacs/cider-nrepl#537] opened 2018-07-10 20:21 UTC
Looks like a new version of 0.18.0-SNAPSHOT was pushed today that breaks cider-nrepl. 0.17.0 isn't affected, nor was 0.18.0-SNAPSHOT prior to today.

```
java -version
java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

```
/usr/local/bin/clojure -Sdeps '{:deps {org.clojure/tools.nrepl {:mvn/version "0.2.13"} refactor-nrepl {:mvn/version "2.4.0-SNAPSHOT"} cider/cider-nrepl {:mvn/version "0.18.0-SNAPSHOT"}}}'  -e '(require (quote cider-nrepl.main)) (cider-nrepl.main/init ["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"])'
Exception in thread "main" java.lang.IllegalArgumentException: No matching ctor found for class java.net.InetSocketAddress
        at clojure.lang.Reflector.invokeConstructor(Reflector.java:183)
        at clojure.tools.nrepl.server$start_server.invokeStatic(server.clj:141)
        at clojure.tools.nrepl.server$start_server.doInvoke(server.clj:121)
        at clojure.lang.RestFn.invoke(RestFn.java:512)
        at cider_nrepl.main$start_nrepl.invokeStatic(main.clj:39)
        at cider_nrepl.main$start_nrepl.invoke(main.clj:31)
        at cider_nrepl.main$init.invokeStatic(main.clj:55)
        at cider_nrepl.main$init.invoke(main.clj:51)
        at user$eval1096.invokeStatic(NO_SOURCE_FILE:1)
        at user$eval1096.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7025)
        at clojure.core$eval.invokeStatic(core.clj:3206)
        at clojure.main$eval_opt.invokeStatic(main.clj:291)
        at clojure.main$eval_opt.invoke(main.clj:285)
        at clojure.main$initialize.invokeStatic(main.clj:311)
        at clojure.main$null_opt.invokeStatic(main.clj:345)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
```

**Comment by dpsutton** [comment] 2018-07-10 20:44
@hagmonk if you have time do you think you could try this without the refactor-nrepl dep just to make sure its not a clash there?

**Comment by hagmonk** [comment] 2018-07-10 20:45
I ran a `git bisect` and confirmed it's 4a6be9f.

**Comment by arichiardi** [comment] 2018-07-10 20:46
Weird I did not get that error at all. Out and about now. Cannot double check.

**Comment by hagmonk** [comment] 2018-07-10 20:55
It seems `cider-nrepl.main/start-nrepl` now expects to receive a map of options, whereas cider's clojure-cli invocation passes a vector of handlers: `(cider-nrepl.main/init ["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"])`

This causes `nrepl.server/start-server` to be passed a `:port` of `nil`. This kills the crab.

**Comment by cjsauer** [comment] 2018-07-10 21:00
Also having this issue and traced the code a bit. It looks like `cider-nrepl.main/init` used to take a sequence of middleware symbols as its argument, which has been changed to an `opts` map in commit https://github.com/clojure-emacs/cider-nrepl/commit/4a6be9f8a5e2a97bed95d959188f0e470f98aab1. `cider-jack-in` (at least using tools.deps, I haven't tested with lein) is still using the old signature, mainly:

```
clojure -Sdeps '{:deps {org.clojure/tools.nrepl {:mvn/version "0.2.13"} com.billpiel/sayid {:mvn/version "0.0.16"} refactor-nrepl {:mvn/version "2.4.0-SNAPSHOT"} cider/cider-nrepl {:mvn/version "0.17.0"}}}' -e '(require (quote cider-nrepl.main)) (cider-nrepl.main/init ["com.billpiel.sayid.nrepl-middleware/wrap-sayid", "refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"])'
```

**Comment by arichiardi** [comment] 2018-07-10 21:06
The port should not be a problem, there should be a patch already in for that.

**Comment by hagmonk** [comment] 2018-07-10 21:09
I just rushed through a quick PR, I didn't follow all the guidelines to the letter :) Hopefully it's useful, just wanted to help expedite things.

**Comment by arichiardi** [comment] 2018-07-10 22:43
I see now what happened, this update got pushed without the changes in cider...so I don't know if the right fix is to update things here. It seems to me the best course of action would be to update the tasks.

**Comment by arichiardi** [comment] 2018-07-10 22:45
The rationale behind the option map is of course to make the function more flexible and more customizable with params...I should have followed suit with cider tasks but went to holiday so I could not.

Sorry for the (snapshot) breakage!

**Comment by SevereOverfl0w** [comment] 2018-07-11 05:38
I would like to see the fix applied here and not in cider Emacs. My vim jack in plugin has no awareness of cider versions, so can't change behaviour on a version.

Two functions seems okay, even if one needs a comment to mention that it's for backwards compatibility.

**Comment by bbatsov** [comment] 2018-07-11 05:41
> The port should not be a problem, there should be a patch already in for that.

The problem is that this was fixed in `nrepl/nrepl`, but we're still not using it yet. That's going to happen in the next release (0.19).

> Two functions seems okay, even if one needs a comment to mention that it's for backwards compatibility.

Yeah, that seems reasonable to me. We'll just use a different function for the extended behaviour added by @arichiardi and update CIDER to use it.

**Closed** 2018-07-11 05:49 UTC

**Comment by arichiardi** [comment] 2018-07-11 15:17
Awesome folks thanks
