### ISSUE TITLE
Can't build cider-nrepl with lein 2.8.0: source-deps task is broken

### ISSUE THREAD

**Issue by pdbrown** [clojure-emacs/cider-nrepl#449] opened 2017-10-30 03:35 UTC
## Expected behavior
When building cider-nrepl from source using leiningen 2.8.0, one should be able to build inline deps with the manderson plugin, as per https://github.com/clojure-emacs/cider-nrepl#working-with-mranderson-inlining-dependencies. Works with lein 2.7.1:
```
$  lein source-deps :project-prefix cider.inlined-deps
project prefix:  cider.inlined-deps
retrieve dependencies and munge clojure source files
  retrieving tools.trace artifact.
...
```
## Actual behavior
With lein 2.8.0, building source deps fails:
```
$  lein source-deps :project-prefix cider.inlined-deps
java.lang.ClassCastException: Cannot cast org.apache.maven.repository.internal.DefaultVersionResolver to org.sonatype.aether.impl.VersionResolver
        at java.lang.Class.cast(Class.java:3369)
        at org.sonatype.aether.impl.internal.DefaultServiceLocator.getServices(DefaultServiceLocator.java:161)
        at org.sonatype.aether.impl.internal.DefaultServiceLocator.getService(DefaultServiceLocator.java:133)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.initService(DefaultRepositorySystem.java:142)
        at org.sonatype.aether.impl.internal.DefaultServiceLocator.getServices(DefaultServiceLocator.java:181)
        at org.sonatype.aether.impl.internal.DefaultServiceLocator.getService(DefaultServiceLocator.java:133)
        at mranderson047.pomegranate.v0v3v0.cemerick.pomegranate.aether$repository_system.invokeStatic(aether.clj:110)
        at mranderson047.pomegranate.v0v3v0.cemerick.pomegranate.aether$repository_system.invoke(aether.clj:108)
        at mranderson047.pomegranate.v0v3v0.cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic(aether.clj:691)
...
```
which causes additional exceptions, see [stacktrace.txt](https://github.com/clojure-emacs/cider-nrepl/files/1425867/stacktrace.txt)

This seems like a classpath issue, as leiningen changed it's dependencies from 2.7.1 -> 2.8.0. I couldn't fix the problem with a first-order attempt at fiddling with exclusions and forced versions, but someone who knows how manderson/pomegranate/aether/maven/leiningen interact might. Once this is figured out, it would be nice to add a `:pedantic? :abort` entry to the build as well.

### cider-nrepl version

0.16.0-SNAPSHOT @ ce42411

### Java version

openjdk 1.8.0_131

### Operating system

Debian 4.9.30-2+deb9u2

**Comment by bbatsov** [comment] 2017-10-30 07:58
@benedekfazekas Any ideas?

**Comment by bbatsov** [comment] 2017-10-30 08:00
Looking at the stacktrace it seems to me the problem is with pomegranate. I guess the updated deps broke something there.

**Comment by benedekfazekas** [comment] 2017-10-30 10:03
yup @bbatsov it seems that the deps upgrades with leiningen broke it. will try to have a look this week.

**Comment by SevereOverfl0w** [comment] 2017-11-06 16:51
This can be fixed by simply updating pomegranate in mr anderson (and cider-nrepl's dependency on mr anderson)

**Comment by bbatsov** [comment] 2017-11-19 08:09
I assumed as much. I hope @benedekfazekas will cut a new release soon.

**Comment by benedekfazekas** [comment] 2017-11-19 08:15
will do. sorry extremely busy lately :/

On 19 Nov 2017 8:09 a.m., "Bozhidar Batsov" <notifications@github.com>
wrote:

I assumed as much. I hope @benedekfazekas
<https://github.com/benedekfazekas> will cut a new release soon.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/clojure-emacs/cider-nrepl/issues/449#issuecomment-345499458>,
or mute the thread

**Comment by benedekfazekas** [comment] 2017-11-23 22:52
well, the mranderson version upgrade still needs to be merged here, so a bit early to close this

**Comment by bbatsov** [comment] 2017-11-24 10:46
@SevereOverfl0w Can you take a look at the open PR? We're facing some mysterious problems and unfortunately I don't have time to investigate them.

**Closed** 2017-11-24 12:04 UTC

**Comment by SevereOverfl0w** [comment] 2017-11-25 16:57
I'll take a look now.

**Comment by SevereOverfl0w** [comment] 2017-11-25 17:36
This seems related to https://dev.clojure.org/jira/browse/NREPL-87 & https://github.com/travis-ci/travis-ci/issues/3302

I'm still figuring a concrete fix out, but reporting here in case I don't get time to finish it up.
