### ISSUE TITLE
debugger fails to instrument consistently via external request (i.e. curl)

### ISSUE THREAD

**Issue by rcullito** [clojure-emacs/cider-nrepl#429] opened 2017-07-16 18:22 UTC
## Expected behavior
Instrumented functions, via `C-u C-M-x` should pause execution when the underlying code is called, regardless of whether the process is started via the repl or is external (such as a curl request against a ring application)

## Actual behavior
a.) if instrumentation does occur from a http reuqest, it only happens once when the nrepl is first started, but after hitting c for "continue", subsequent curl or http requests do not cause instrumentation. 
- also, some more deeply nested calls fail to instrument in the first place via http call. 

## Steps to reproduce the problem
I'm happy to create an example web app to highlight the problem, but first I was curious if this is a known entity and debugging should not be expected when the source of the call is outside of the repl itself?

### cider-nrepl version
0.15.0-SNAPSHOT

### Java version
1.8

### Operating system
mac os x sierra 10.12.3

**Comment by vspinu** [comment] 2017-08-19 00:05
This is a very likely duplicate of clojure-emacs/cider#1869 but we still don't have a self-contained reproducible example of the issue.

**Comment by Malabarba** [comment] 2017-08-19 14:52
I used to debug web requests all the time, so the bug is probably a little more subtle. As vspinu said, an isolated reproducible example would help a lot.

**Closed** 2018-07-16 16:02 UTC
Labels: debugger
